version: "3"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "1234567890"
    ports: 
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    ports:
      - 8080:8080